const mockedInsurances = [
  {
    insuranceCalculations: {
      basePrice: 130,
      totalPrice: 233.6,
      bonusProtection: 15.6,
      autoLiability: 0,
      glassProtection: 88,
      commercialDiscount: 13,
      agentsDiscount: 0,
      vipDiscount: 0,
      strongCarSurcharge: 13,
      voucher: 0,
    },
    customerName: "Luka",
    birthdate: "2024-02-16",
    city: "Zagreb",
    vehiclePower: 110,
    voucher: 0,
    activeDiscounts: ["strongCarSurcharge", "commercialDiscount"],
    activeCoverages: ["glassProtection", "bonusProtection"],
    totalPrice: 233.6,
    id: "65d25bfff299e40aa9b38fb7",
  },
  {
    customerName: "Pero",
    birthdate: "1978-06-15T00:00:00.000Z",
    city: "Osijek",
    vehiclePower: 70,
    voucher: 0,
    activeDiscounts: ["commercialDiscount"],
    activeCoverages: ["glassProtection", "bonusProtection"],
    totalPrice: 331.4,
    insuranceCalculations: {
      basePrice: 270,
      totalPrice: 331.4,
      agentsDiscount: 0,
      autoLiability: 0,
      bonusProtection: 32.4,
      commercialDiscount: 27,
      glassProtection: 56,
      vipDiscount: 0,
      strongCarSurcharge: 0,
      voucher: 0,
    },
    id: "65d28badf299e40aa9b3912e",
  },
];

export default mockedInsurances;
